### ISSUE TITLE
Unable to open CTFAK using the released build.

### ISSUE THREAD

**Issue by SuperGamingAliYT** [CTFAK/CTFAK2.0#10]
When I try to open the program nothing opens. I tried to Run it as Administrator but still nothing.

**Comment by AITYunivers** [comment]
Works fine on Windows 11 for me. Do you have .NET 6.0 Runtime installed?

**Comment by SuperGamingAliYT** [comment]
yes

**Comment by AITYunivers** [comment]
Are you building it yourself or using the released version? If using the released version, are you actually unzipping it?

**Comment by SuperGamingAliYT** [comment]
I'm using the released version

**Comment by AITYunivers** [comment]
Can you run ctfak.cli.exe via command prompt and see what error it's outputting, if any?

**Comment by SuperGamingAliYT** [comment]
do you mean ctfak.cli.pdb?

**Comment by AITYunivers** [comment]
No, I mean CTFAK.Cli.exe
![image](https://user-images.githubusercontent.com/92553545/187125916-2cb0161b-4184-4366-8e94-c21bfcd66dd1.png)

**Comment by SuperGamingAliYT** [comment]
ah, yeah that's the one I'm having the problem with. No, nothing shows up including errors.

**Comment by AITYunivers** [comment]
Is it works for me, and I'm on Windows 11, I don't know how I can help if you're not getting any errors. I'll leave this for someone else.

**Comment by Tomek839839** [comment]
I have exactly the same problem, running as administrator doesn't help, I use Windows 10 and I have Microsoft .NET Runtime - 6.0.9 installed.

**Comment by charuse** [comment]
I also have the same problem, I installed all versions of .NET 6.0.9

**Comment by userjust13** [comment]
I indeed too have that.

**Comment by lily-snow-9** [comment]
You need 6.0.6

**Comment by charuse** [comment]
> You need 6.0.6

Does not fix it, same thing happens with 6.0.6 and 6.0.9

**Comment by SpookLad** [comment]
Can confirm, this issue still occurs. I have .NET 6.0.6, and I even tried to run it through CMD. Even then, literally nothing happens.

**Comment by lily-snow-9** [comment]
What's the file size?

**Comment by charuse** [comment]
> What's the file size?

CTFAK.Cli.exe is 168KB, the folder with CTFAK after extracting is 6.8 MB.

**Comment by UnknownAMD** [comment]
> Can confirm, this issue still occurs. I have .NET 6.0.6, and I even tried to run it through CMD. Even then, literally nothing happens.

try ASP.net 6.0.6 instead

**Comment by misha99fr** [comment]
why i can't decompile fnbf apk without -noevnt parametr

**Comment by AITYunivers** [comment]
Closing as this is User Error. Make sure you have both ASP.NET Core Runtime 6.0.11 and .NET Desktop Runtime 6.0.11 downloaded and installed.
