### ISSUE TITLE
How do you use the excludeframe([id]) parameter?

### ISSUE THREAD

**Issue by Jorgegam1295** [CTFAK/CTFAK2.0#108]
I tried to use it in a game by putting the ids as numbers, then I tried to put the name (example: "menu") but it didn't work either, does anyone know how to use it correctly?
I have another question, is it possible to put more than one id?

**Comment by AITYunivers** [comment]
![image](https://github.com/CTFAK/CTFAK2.0/assets/92553545/e106be2b-9651-4daf-bcef-5c0e4f1637b2)

**Comment by Jorgegam1295** [comment]
I mean, id is frame 0? And if so, if I replace "id" with 1, is frame 1 skipping? (I'm translating this because I speak little English so forgive me if I don't understand CTFAK as much lmao)

**Comment by AITYunivers** [comment]
The id is the index of the frames
Say you have a game where this is the games workspace

- Splash
- Warning
- Title
- Level Select
- Loading
- Level
- Battle
- Cutscenes
- Endings
- Credits

if your CTFAK parameter input is then
`-excludeframe(4) -excludeframe(7) -excludeframe(8)`

it will output

- Splash
- Warning
- Title
- Level Select
- Level
- Battle
- Credits

**Comment by Jorgegam1295** [comment]
Thank you very much (I hadn't tried removing "[]")
