### ISSUE TITLE
CTFAK only dumping some images.

### ISSUE THREAD

**Issue by MysticTortoise** [CTFAK/CTFAK2.0#18]
Title. Most objects dump only the first frame of the first animation, and then dump the rest of the images completely blank (as in, it dumps the image with the right names, dimensions etc., but the image itself is completely transparent.)
This happens even using the -noevnt and -noalpha parameters. Happens on all games I've tested (only around 3 or 4)
Doesn't matter if I'm using regular image dumper, sorted image dumper, or the full Decompile. Happens on latest release version.

**Comment by lily-snow-9** [comment]
fix 4 do be like that

**Comment by AITYunivers** [comment]
shut up liz

**Comment by lily-snow-9** [comment]
lel ok

**Comment by AITYunivers** [comment]
Anyway, ask Liz for their fix. lol
Seems like my method doesn't work for some people. It's very odd. I've only encountered the issue on Popgoes 2016

**Comment by lily-snow-9** [comment]
then im the dumb one

**Comment by AITYunivers** [comment]
You thought I was the lead dev, so yes. 🤡

**Comment by lily-snow-9** [comment]
Kostya said so 🤡

**Comment by AITYunivers** [comment]
Kostya is a clown 🤡

**Comment by lily-snow-9** [comment]
LOL

**Comment by MysticTortoise** [comment]
this is great

**Comment by AITYunivers** [comment]
Liz! Fix their issue!

**Comment by lily-snow-9** [comment]
no

**Comment by AITYunivers** [comment]
Kostya, Fix your image bank!

**Comment by lily-snow-9** [comment]
yes

**Comment by AITYunivers** [comment]
![image](https://user-images.githubusercontent.com/92553545/198478709-1fe1899d-5694-45e3-b7e8-8ddcb5363619.png)

**Comment by AITYunivers** [comment]
Anywho, despite was Liz thinks, I didn't break it. It was much more unstable before I made changes and using -noalpha reverts it to how Kostya had it.

**Comment by lily-snow-9** [comment]
yes u didnt break it, it was always broken

**Comment by MysticTortoise** [comment]
...."This happens even using the -noevnt and -noalpha parameters."

**Comment by AITYunivers** [comment]
I know Mystic
I was gonna say that before Liz interrupted

**Comment by AITYunivers** [comment]
I love GitHub's live updates! It's like a worse Discord!

**Comment by AITYunivers** [comment]
Anyways, while Kostya spends 24/7 trying to fix it, Imma go play Genshin Impact bc **I'm not the lead dev**.

**Comment by MysticTortoise** [comment]
Thanks, nice to know this isn't just an issue on my end.

**Comment by AITYunivers** [comment]
Use Source Explorer for now.

**Comment by MysticTortoise** [comment]
No sorted image dumps and no full decompile for 2.5+ ;(

**Comment by AITYunivers** [comment]
Yeah that's bc LAK sucks at everything CTFAK's good at, and CTFAK sucks at everything LAK's good at.

**Comment by AITYunivers** [comment]
Closing, this is fixed but a real release with it probably won't be public for a while.
