### ISSUE TITLE
Clickteam Fusion 2.5+ Game Decompile Question

### ISSUE THREAD

**Issue by brandzone-kreativagentur** [CTFAK/CTFAK2.0#26]
Hello,
could someone try to decompile following Clickteam Fusion 2.5+ Games or have an idea how to adjust existing Decompiler?

https://www.mediafire.com/file/fdwundtts2ow8yo/CTF_Games.7z/file

THX

**Comment by AITYunivers** [comment]
This not an issue. Reopen with the issue you are having.
