### ISSUE TITLE
Internal CLI Error

### ISSUE THREAD

**Issue by MAS0451X** [CTFAK/CTFAK2.0#30]
When I try to decompile using CTFAK2.0, it throws an error and then it close.
![Screenshot (1)](https://user-images.githubusercontent.com/117832675/208265420-1ded8f48-8ef7-40d4-93cc-4689083358bb.png)

**Comment by AITYunivers** [comment]
No clue

**Comment by MAS0451X** [comment]
It decompiles successfully using Source Explorer's program, but when I try to decompiles it using CTFAK2.0 it just closes.
I can send the EXE file for testing.
Also, I tried to copy the dump from Source Explorer to CTFAK2.0, but it still throws that error.

**Comment by AITYunivers** [comment]
No clue, like I said.
That's not really an error I know how to debug.

**Comment by 1987kostya1** [comment]
Something funny happened to the image translation library. Do you know what color mode is used by the game?

**Comment by AITYunivers** [comment]
If it's 2.5+ it forces to read as 16m, bc kostya

**Comment by 1987kostya1** [comment]
No, I don't translate 32-bit images with the native lib I think. I might be wrong. Anyways, it would be easier to figure out why that happens if I had the game

**Comment by AITYunivers** [comment]
![image](https://user-images.githubusercontent.com/92553545/208291631-7b5834a8-b2ef-44d2-aec8-c658fdbbd38f.png)

**Comment by MAS0451X** [comment]
Here is the link to the game :-
[http://www.mediafire.com/file/b834kelhkf6md7f/jollibees-phase-2-1.32.exe/file](url)

**Comment by MAS0451X** [comment]
I also noticed that it only extracts the shaders, and then it closes.
It says when opening the shader's xml file :-
`<effect>
<name>CS_Saturation0</name>
<author>Unknown</author>
<description>Generated by CTFAK, all credits to original author</description>
<BackgroundTexture>512</BackgroundTexture>
<sampler>
<index>0</index>
<filter>linear</filter>
</sampler>
</effect>`

**Comment by AITYunivers** [comment]
That's because it extracts the shaders first.

**Comment by MAS0451X** [comment]
And then it extracts the images, right?
Is there anyway that I can provide the extracted files, and only make CTFAK2.0 compile it into MFA file?
