### ISSUE TITLE
Dump android application.ccn gives error

### ISSUE THREAD

**Issue by ghyath5** [CTFAK/CTFAK2.0#32]
![image](https://user-images.githubusercontent.com/49321826/209428201-05525512-fcb7-43de-bbbf-b7dd887c4c17.png)

Unhandled exception. System.IO.IOException: An attempt was made to move the position before the beginning of the stream

**Comment by AITYunivers** [comment]
CTFAK does not officially support Android Clickteam Fusion games made in 2.5+
Use `-noevnts` as a parameter. If you get issues with images, use 2.2 not 2.3.

Closing because this isn't an issue, we just don't support it yet.
