### ISSUE TITLE
Opening For A Second Then Closes

### ISSUE THREAD

**Issue by SuperGamingAliYT** [CTFAK/CTFAK2.0#34]
I compiled the program with no issues and when I try to open CTFAK.Cli, it keeps closing after a second. I've recorded it and uploaded it here: https://youtu.be/VpzdW0VU9hA

Edit: I have .NET 6.0 installed.

**Comment by AITYunivers** [comment]
1. We never recommend attempting to compile CTFAK yourself, please use [this release](https://github.com/CTFAK/CTFAK2.0/actions/runs/3697502725) instead.
2. You failed to compile CTFAK and lack important files required by CTFAK, please refer to 1.
3. Make sure you have .NET 6.0's Core Runtime and .NET 6.0's Desktop Runtime as CTFAK cannot function without them.
4. You are told the exact issue if you open CTFAK.Cli via the command prompt.

**Comment by AITYunivers** [comment]
If none of these 4 suggestions work for you, Feel free to reopen this issue with more specifics.
