### ISSUE TITLE
Opening For A Second Then Closes

### ISSUE THREAD

**Issue by SuperGamingAliYT** [CTFAK/CTFAK2.0#35]
I have opened this issue once but I didn't do a good job at the specifications so here is better explained version.

I have download the release and when I opened it would close after a second. After opening it via CMD it gave me this error that I put in a .txt file.
[ctfak error log.txt](https://github.com/CTFAK/CTFAK2.0/files/10798647/ctfak.error.log.txt)

I also have a video of it happening
https://user-images.githubusercontent.com/110069000/220483100-28a8fb13-2dff-4221-940f-a839bbd67599.mp4

Note: I have .NET 6.0's Core Runtime and .NET 6.0's Desktop Runtime Installed.

**Comment by AITYunivers** [comment]
Extract ctfakrequirements.zip

**Comment by AITYunivers** [comment]
You don't need to make a new issue every time you wanna reopen this, just type a reply then click reopen.

**Comment by SuperGamingAliYT** [comment]
1: Sorry I didn't know that.
2: I extracted the .zip file and it shows me the same errors.

**Comment by AITYunivers** [comment]
It needs to be extracted to root, not it's own folder.

**Comment by SuperGamingAliYT** [comment]
Thank You. It works now. Sorry for the inconvenience.
