### ISSUE TITLE
where do I find the mfa after decompilling

### ISSUE THREAD

**Issue by justbasicisaaccase** [CTFAK/CTFAK2.0#41]
I am just wondering where do I find the mfa. in the dumps folder it only shows the shaders, but I want the mfa only. where do I find that?

**Comment by AITYunivers** [comment]
Did you actually run the decompiler or did you only read the exe.

**Comment by justbasicisaaccase** [comment]
I opened the exe and pressed enter twice, it showed all the frame names but what do I do after that?

**Comment by AITYunivers** [comment]
it should show you a screen similar to this 
![image](https://user-images.githubusercontent.com/92553545/232120580-c305e357-8dca-41fb-a80f-d735817df1ac.png)
Just press '1' then press 'Enter' then it'll decompile.

**Comment by justbasicisaaccase** [comment]
ok let me try that

**Comment by justbasicisaaccase** [comment]
it just shows the frame names

**Comment by AITYunivers** [comment]
then it's not done loading. give it time.

**Comment by justbasicisaaccase** [comment]
ok

**Comment by justbasicisaaccase** [comment]
it crashes and then shows a popup and then only saves the shaders

**Comment by AITYunivers** [comment]
dumps

**Comment by justbasicisaaccase** [comment]
its not there
only the shaders from the last game I tried

**Comment by AITYunivers** [comment]
did the decompiler run

**Comment by justbasicisaaccase** [comment]
yes, it said "execution of decompiler finished in 7.4 seconds"

**Comment by AITYunivers** [comment]
If it's not in the dumps folder, I can't help you. It should be there, I can't just magically make it be there.

**Comment by justbasicisaaccase** [comment]
wait when i closed it it started saving, I think it worked!
