### ISSUE TITLE
FNF ONLINE VS 0.4.5 - decompiled images are heavily corrupted

### ISSUE THREAD

**Issue by doggogit** [CTFAK/CTFAK2.0#42]
Hello, me and a friend have tried to decompile FNF ONLINE VS 0.4.5 using CTFAK, both the `main` and `CTFAK-2.3` branch.

The game decompiles fine, however, upon opening in Clickteam Fusion Developer 2.5+, whenever a frame is inspected/opened, all of the images are corrupted, despite all of the systems and audio working fine.

[Link to FNF ONLINE VS](https://gamebanana.com/mods/286594).

In addition, multiple people/computers have attempted this and the result is the same.

**Comment by AITYunivers** [comment]
CTFAK is in the middle of an image bank rewrite. This is already in the process of being fixed.

**Comment by doggogit** [comment]
Sweet! Will look forward to future updates.
