### ISSUE TITLE
CTFAK.Cli closes a milisecond after start up

### ISSUE THREAD

**Issue by doggogit** [CTFAK/CTFAK2.0#43]
Following 334b3cc on the `CTFAK-2.3` branch, `CTFAK.Cli` closes right after it starts up.

It doesn't throw out any errors, it just opens for a really short amount of time and closes *immediately* after.

However, the `CTFAK.Interactive` version works.

[And yes, I do have .NET 7.0 installed](https://user-images.githubusercontent.com/115869532/233640604-342a8773-9dbb-46d2-a727-6ef9e3960f9f.png).

Any way to fix this?

**Comment by 1987kostya1** [comment]
CTFAK.Cli uses .net6.0

**Comment by doggogit** [comment]
[But in the README it says this](https://user-images.githubusercontent.com/115869532/233649590-4bd0ea80-a5f3-4f10-b9a3-8fac49c57ca5.png).

**Comment by 1987kostya1** [comment]
I'll ask Yuni to fix the readme. Only CTFAK.Interactive uses .net7.0

**Comment by doggogit** [comment]
Alright, thanks! Will download .NET 6.0 and try out CTFAK.Cli. 👍

**Comment by 1987kostya1** [comment]
If you're new to CTFAK - you should try CTFAK.Interactive first, because it's basically a better version of CTFAK.Cli

**Comment by doggogit** [comment]
> If you're new to CTFAK - you should try CTFAK.Interactive first, because it's basically a better version of CTFAK.Cli

I've had no issues running either before, but thanks for the suggestion anyways.
