### ISSUE TITLE
FNF ONLINE VS 0.4.5 - decompiler doesn't work, throws out an error and doesn't spit out a .mfa file

### ISSUE THREAD

**Issue by doggogit** [CTFAK/CTFAK2.0#44]
Hello, sorry for opening a ton of issues regarding this application, but we've been waiting for months to decompile this game and this is the only program that's come super close to completing that task.

Using `CTFAK-2.3`, from commit 334b3cc, reading the game's .exe file works fine [but attempting to decompile. it throws out this error](https://user-images.githubusercontent.com/115869532/233652979-6e353e3f-46a6-44c9-9d08-1b11829b7c6e.png).

Tried this on both `Interactive` and `Cli`, same error.

Is this the fault of the application I'm trying to decompile or is it CTFAK?

Again, sorry for opening so many issues, lol.

**Comment by doggogit** [comment]
> If the game is made with Fusion and decompiling it results in a error - it's always CTFAK's fault. Thank you for reporting the issue, I'll look into it as soon as I can

[Here's some basic information using Source Explorer](https://user-images.githubusercontent.com/115869532/233675654-25044d0e-aab9-4cbc-a47b-3d691306a1a7.png).

But, as far as I'm aware, yes, it's made with Clickteam Fusion.

**Comment by doggogit** [comment]
> I'm gonna close this, as using the `-noicons` parameter fixes this problem. Also for reference, next time you have 2 of the same issues, reopen the old one, don't make a new one. Also, opening the mfa is going to give you some errors, just ignore them. Any deleted frames means you don't have an extension installed. If you really need help with that, join the discord, don't create an issue.
> 
> Also, **CTFAK does not condone or support using it's tools to create cheated clients of multiplayer games.**

Thank you for all your help! I would like to, first and foremost, say that we aren't decompiling this program for the sake of making CHEATS for it.

It's mostly for porting it to a new engine, HaxeFlixel.

Again, thank you for your help.

**Comment by AITYunivers** [comment]
why would you do something so stupid

**Comment by 1987kostya1** [comment]
HaxeFlixel is the engine that is used by the original FNF btw

**Comment by AITYunivers** [comment]
Yes, I know this Kostya

**Comment by doggogit** [comment]
I'm ending the conversation here.

Just know, we aren't using CTFAK for any malicious intent.

That is all.
