### ISSUE TITLE
I'm at a loss...Please see attached and Thank You

### ISSUE THREAD

**Issue by Randombirdnoise** [CTFAK/CTFAK2.0#47]
[Latest.log](https://github.com/CTFAK/CTFAK2.0/files/11325935/Latest.log)

**Comment by AITYunivers** [comment]
that tells us nothing.

**Comment by 1987kostya1** [comment]
You just gotta wait, it's loading the imagebank and it takes some time

**Comment by AITYunivers** [comment]
This was closed due to inactivity. Don't reopen shit if you have no reason to.
