### ISSUE TITLE
does the ctfak in MineOS official? opencomputers mod

### ISSUE THREAD

**Issue by misha99fr** [CTFAK/CTFAK2.0#55]
![image](https://github.com/CTFAK/CTFAK2.0/assets/83592338/2ee2a3ad-c86b-4ef1-a767-dae5b3b015e9)

**Comment by 1987kostya1** [comment]
no, it's an absolute garbage that is trying to get attention by using the name of our project

**Comment by Fadeyauso** [comment]
> ![image](https://user-images.githubusercontent.com/83592338/253008466-2ee2a3ad-c86b-4ef1-a767-dae5b3b015e9.png)

bro get lost

**Comment by misha99fr** [comment]
who tf are u
