### ISSUE TITLE
packed data not unpacking

### ISSUE THREAD

**Issue by Fadeyauso** [CTFAK/CTFAK2.0#56]
pack data is not being decompressed.

all files start with 7b which is a zlib header.

**Comment by Fadeyauso** [comment]
game is post shift 2

**Comment by AITYunivers** [comment]
send latest.log

**Comment by AITYunivers** [comment]
Nevermind already fixed in the next version of 2.2.
![image](https://github.com/CTFAK/CTFAK2.0/assets/92553545/6abc440d-8c85-42a1-b3a2-a71bd7b2f22a)
