### ISSUE TITLE
An error occurred while loading frame #X

### ISSUE THREAD

**Issue by gamerbross** [CTFAK/CTFAK2.0#59]
After exporting the MFA of any game, I get this error for every frame: “An error occured while loading frame #x” (yeah, they typed “occured” and not “occurred”)
![image](https://github.com/CTFAK/CTFAK2.0/assets/55158797/df2add02-5d53-4ef4-b2bc-d13aaef8bc9d)
Maybe it's because of my Fusion version, “Clickteam Fusion Developer 2.5 (Build R284.10) (Unicode)”

**Comment by AITYunivers** [comment]
![youareanidiot](https://github.com/CTFAK/CTFAK2.0/assets/92553545/4bff5b96-1ebf-4dc7-bef1-40e5fee8f92c)
