### ISSUE TITLE
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')

### ISSUE THREAD

**Issue by MaxKotovov** [CTFAK/CTFAK2.0#72]
![image](https://github.com/CTFAK/CTFAK2.0/assets/127125279/cfb6454b-a830-4d2b-abd6-5ea7b2e44fd8)
[Latest.log](https://github.com/CTFAK/CTFAK2.0/files/12361778/Latest.log)

**Comment by feiran-wang** [comment]
same problem

**Comment by AITYunivers** [comment]
Duplicate of #48
