### ISSUE TITLE
Program caused my monitor to look pixelated.

### ISSUE THREAD

**Issue by JPTOfficiaL** [CTFAK/CTFAK2.0#76]
Screen was working just fine before I installed and ran the program, but after I opened it, it seems to look like this now.
![IMG_1230](https://github.com/CTFAK/CTFAK2.0/assets/146243822/2b5d8c06-bf99-42d4-8d8f-5ee1c2be62f7)

yes, I tested this on another monitor, and it looked normal, but my monitor never had any issues until I installed the program.
now I uninstalled the program, but I'm worried that if I run this again, it'll look even worse.

**Comment by AITYunivers** [comment]
Looks like your ram is dying to me. Lol

**Comment by JPTOfficiaL** [comment]
I have 32GB of ram and it was installed when I built my pc over a year ago

**Comment by AITYunivers** [comment]
Well it's either a hardware issue or CTFAK is a magical virus from neverland and you need to gather Peter Pan and his Lost Boys to fix it!
