### ISSUE TITLE
Clickteam failes to open mfa file with no error and reason why it does

### ISSUE THREAD

**Issue by donotprikel231** [CTFAK/CTFAK2.0#77]
I use CTFAK version 2.2 and i export as mfa when done i open mfa in clickteam fusion developer and it says 

![Screenshot (319)](https://github.com/CTFAK/CTFAK2.0/assets/118140095/b8e73955-0c6e-4c41-bc88-0d957314c6fa)
![Screenshot (320)](https://github.com/CTFAK/CTFAK2.0/assets/118140095/33a72a98-abdc-4253-82c5-aa9364548b8b)
![Screenshot (321)](https://github.com/CTFAK/CTFAK2.0/assets/118140095/32fefe75-05be-48ba-bdff-bb6ef5bbe657)

Theres NO MSG BOX SAYING I NEED TO INSTALL AN EXTENTION OR ANYTHING ELSE ON HOW TO FIX. Ive repaird the mfa file with no luck and I CANNOT MAKE CLICKTEAM FUSION LOAD HIGHER MFA FILE SIZES. THe project size is 436 MB. I dont know if its CTFAK or clickteam fusion Or the mfa file

**Comment by 1987kostya1** [comment]
don't use pirated fusion ;)

**Comment by donotprikel231** [comment]
WHat are you talking about? I don't even know where you saw that or if
you're lying. I've gotten a computer from my friend and he had that
software on it so I transferred it onto my computer and I use it all the
time. I don't know where you saw that and if it is pirated i'll buy the
software from steam.

**Comment by AITYunivers** [comment]
LOL, We know it's pirated because it's a common pirated version and looks nothing like what Clickteam Fusion looks like today.

**Comment by donotprikel231** [comment]
I'm using an older version I did not know. My friend is going to get into
HUGE trouble if it's pirated. I'll buy the software on steam as soon as
possible
