### ISSUE TITLE
Argument Out of Range Exception

### ISSUE THREAD

**Issue by Cerium06** [CTFAK/CTFAK2.0#78]
Every time I attempt to decompile Oblitus Casa 2.0 I get this error.
![err](https://github.com/CTFAK/CTFAK2.0/assets/113068596/3fb0d6d8-bd03-4573-9359-f609823339f2)

**Comment by AITYunivers** [comment]
Oblitus Casa 2.0 has anti-decompilation methods and will not be supported.

**Comment by donotprikel231** [comment]
You can use render doc to capture a frame with textures on it then export them BUT You would have to do each texture 1 by 1 capturing every frame then compare for duplicates then try to capture rare screens then beat the whole game by capturing eatch frame it takes a VERRY long time and is not the best one right now. Im still trying to get a way to do it better but for now
