### ISSUE TITLE
TROLL GAME FOR NIGHTMARE BELOW DISNEY CRASHES DECOMPLIER 

### ISSUE THREAD

**Issue by SelfReflection31** [CTFAK/CTFAK2.0#85]
![CRASHES](https://github.com/CTFAK/CTFAK2.0/assets/113463662/57bf56b2-74ed-4f68-836b-e7d172755d6f)

THE TROLL GAME FOR NIGHTMARE BELOW DISNEY CRASHES CTFAK
CAN BE FIXED?

**Comment by AITYunivers** [comment]
Duplicate of #78
