### ISSUE TITLE
System.IO.EndOfStreamException

### ISSUE THREAD

**Issue by flappybirdplayer29** [CTFAK/CTFAK2.0#89]
this app worked perfectly several times, however, it now says this whenever i open something
![atkerror](https://github.com/CTFAK/CTFAK2.0/assets/148887957/56ab4618-2af0-4bf9-b33f-422d0534035f)

**Comment by AITYunivers** [comment]
You sure it's made in Clickteam Fusion 2.5 and not Multimedia Fusion 2?

**Comment by flappybirdplayer29** [comment]
your right, that one is mmf2. just checked the game page

**Comment by AITYunivers** [comment]
Closing as a duplicate of #16
