### ISSUE TITLE
Crashes upon attempts to open The Desolate Room.

### ISSUE THREAD

**Issue by Btbrid13** [CTFAK/CTFAK2.0#94]
![error](https://github.com/CTFAK/CTFAK2.0/assets/102839218/315d57d3-e925-4dc5-9e81-84f676cdc42c)
This image is what appears before CTFAK crashes, meaning I am unable to attempt to extract the MFA. The game in question is [The Desolate Room](https://gamejolt.com/games/the-desolate-room/96922).

**Comment by AITYunivers** [comment]
MMF 1.5 is not supported.
